import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {Simulation,rangeOf} from '../web/engine.js';
import {EQUIPMENT,ICONS,sweepInterval} from '../web/config.js';

function exercise(options={}){return new Simulation({startAircraft:0,spawnInterval:1e9,scenarioSeconds:1e9,...options});}
function aircraft(sim,n=1){for(let i=0;i<n;i++){const a=sim.spawn(i);a.x=10+i*5;a.y=-100;a.z=2;a.speed=.2;a.angle=Math.PI/2;}}
function measureTwice(sim){for(const a of sim.aircraft)sim.measure(a);sim.time+=6;for(const a of sim.aircraft){a.y+=1.2;sim.measure(a);}sim.allocateTracks();sim.selected=sim.aircraft[0].id;}

test('six detections remain visible with exactly two tracked contacts',()=>{const s=exercise({equipment:{tracks:2}});aircraft(s,6);measureTwice(s);assert.equal(s.contacts.size,6);assert.equal(s.trackCount(),2);const untracked=[...s.contacts.values()].find(c=>!c.tracked);assert.equal(untracked.speed,undefined);const before=s.estimate(untracked);s.time+=2;assert.deepEqual(s.estimate(untracked),before);});
test('estimated movement coasts, then a new measurement corrects it',()=>{const s=exercise();aircraft(s);measureTwice(s);const c=s.getSelected(),before=s.estimate(c);s.time+=3;assert.ok(s.estimate(c).y>before.y);s.aircraft[0].x+=2;s.measure(s.aircraft[0]);assert.equal(s.estimate(c).x,c.history.at(-1).x);assert.equal(c.trackTime,s.time);});
test('selection and detection alone do not permit lock or launch',()=>{const s=exercise();aircraft(s);s.measure(s.aircraft[0]);s.select(s.aircraft[0].id);assert.equal(s.getSelected().allegiance,'UNKNOWN');assert.equal(s.getSelected().recognized,false);s.lock();assert.equal(s.lockAttempt,null);assert.equal(s.fire(),null);});
test('active launch without a hard lock is midcourse, never an instant hit',()=>{const s=exercise();aircraft(s);measureTwice(s);const m=s.fire();assert.ok(m);assert.equal(s.locked,null);assert.equal(m.state,'MIDCOURSE');assert.equal(s.aircraft[0].health,s.cfg.targetHealth);s.step(1);assert.ok(rangeOf(m)>0);assert.ok(m.alive);});
test('seeker search and lock are separate; activation releases a channel',()=>{const s=exercise();aircraft(s);measureTwice(s);const m=s.fire();s.activateSeeker(m,'test');assert.equal(m.state,'SEARCHING');assert.equal(s.channels.size,0);const a=s.aircraft[0];m.x=a.x;m.y=a.y-10;m.z=a.z;m.angle=Math.PI/2;s.step(.1);assert.equal(m.state,'SEARCHING');s.step(1);assert.equal(m.state,'SEEKER LOCK');assert.equal(m.acquired,a.id);});
test('channel overflow displaces oldest active missile, even on one target',()=>{const s=exercise({equipment:{channels:2}});aircraft(s);measureTwice(s);const m1=s.fire();s.launcher=1;const m2=s.fire();s.launcher=2;const m3=s.fire();assert.equal(s.channels.size,2);assert.equal(m1.state,'SEARCHING');assert.equal(m1.channel,false);assert.equal(m2.channel,true);assert.equal(m3.channel,true);assert.ok(s.log.some(l=>l.message.includes('Channel transferred')));});
test('radar OFF switches after delay and launches active early fallback',()=>{const s=exercise();aircraft(s);measureTwice(s);const m=s.fire();s.toggleSensor('radar');s.step(.5);assert.equal(s.radar,true);s.step(2);assert.equal(s.radar,false);assert.equal(m.state,'SEARCHING');assert.equal(m.channel,false);});
test('RESET clears only radar state and preserves missiles, rounds, IRST, aircraft',()=>{const s=exercise();aircraft(s);measureTwice(s);const m=s.fire();s.irst=true;s.updateIr();const reserve=s.reserve,rounds=s.launchers[0].loaded;s.resetRadar();assert.equal(s.contacts.size,0);assert.equal(s.channels.size,0);assert.equal(m.state,'SEARCHING');assert.ok(s.irTracks.size);assert.equal(s.aircraft[0].alive,true);assert.equal(s.reserve,reserve);assert.equal(s.launchers[0].loaded,rounds);});
test('semi-active lock loss coasts before self-destruction',()=>{const s=exercise();aircraft(s);measureTwice(s);assert.equal(s.fire('SEMI_ACTIVE_RADAR'),null);s.locked=s.selected;const m=s.fire('SEMI_ACTIVE_RADAR');assert.ok(m);s.unlock();s.step(1);assert.equal(m.state,'GUIDANCE LOST');assert.equal(m.alive,true);s.step(s.cfg.guidanceLoss+.2);assert.equal(m.alive,false);assert.equal(s.channels.size,0);});
test('semi-active channel overflow does not silently remove displaced missile',()=>{const s=exercise({equipment:{channels:1}});aircraft(s);measureTwice(s);s.locked=s.selected;const first=s.fire('SEMI_ACTIVE_RADAR');s.launcher=1;s.fire('SEMI_ACTIVE_RADAR');s.step(.1);assert.equal(first.alive,true);assert.equal(first.channel,false);assert.equal(first.state,'GUIDANCE LOST');});
test('IR flight uses no battery channel and survives radar RESET and OFF',()=>{const s=exercise();aircraft(s);s.irst=true;s.time=3;s.updateIr();s.time=5;s.updateIr();s.selected=s.aircraft[0].id;s.radar=false;const m=s.fire('IR');assert.ok(m);assert.equal(s.channels.size,0);assert.equal(m.state,'SEARCHING');s.resetRadar();s.step(.2);assert.equal(m.alive,true);assert.equal(m.channel,false);assert.equal(m.guidance,'IR');});
test('auto OFF coasts and expires tracks without refreshing them',()=>{const s=exercise();aircraft(s);measureTwice(s);s.setAuto();const c=s.getSelected(),time=c.trackTime;s.step(7);assert.equal(c.trackTime,time);assert.ok(s.isStale(c));s.step(12);assert.equal(c.tracked,false);assert.ok(s.contacts.size);});
test('rounds consumed from launcher; reloading moves rounds from reserve',()=>{const s=exercise();aircraft(s);measureTwice(s);const reserve=s.reserve;s.fire();assert.equal(s.launchers[0].loaded,3);assert.equal(s.reserve,reserve);s.reload();s.step(s.cfg.reloadSeconds+.1);assert.equal(s.launchers[0].loaded,4);assert.equal(s.reserve,reserve-1);});
test('configured damage can wound at fuze edge and kill at close range',()=>{const s=exercise();const edge=140*s.cfg.damageScale/(.01+s.cfg.fuzeKm**2),close=140*s.cfg.damageScale/.01;assert.ok(edge<s.cfg.targetHealth);assert.ok(close>s.cfg.targetHealth);});
test('complete missile flight can intercept a moving target',()=>{const s=exercise({attackerEvasion:0});aircraft(s);measureTwice(s);const m=s.fire();s.step(110);assert.ok(!m.alive);assert.ok(s.kills>=1,'Expected a physically integrated interception');});
test('scan rating changes revisit interval and leaves supplied ranges intact',()=>{assert.equal(sweepInterval(1),8);assert.equal(sweepInterval(6),2);assert.equal(sweepInterval(3),5.6);assert.equal(EQUIPMENT.detection,455);assert.equal(EQUIPMENT.track,315);assert.equal(EQUIPMENT.missile.range,305);});
test('all canonical icon paths exist with exact ZIP spelling',()=>{for(const name of Object.values(ICONS))assert.ok(fs.existsSync(new URL('../web/assets/'+name,import.meta.url)),name);assert.equal(ICONS.friendlyUnknown,'friendlty_no_ID.png');});
test('semi-active illumination can resume before its loss timer expires',()=>{const s=exercise();aircraft(s);measureTwice(s);s.locked=s.selected;const m=s.fire('SEMI_ACTIVE_RADAR');s.unlock();s.step(1);assert.ok(m.lossTime>0);s.locked=s.selected;s.step(.1);assert.equal(m.lossTime,0);assert.equal(m.state,'ILLUMINATED');assert.equal(m.alive,true);});
test('semi-active retargeting uses illumination and field of view, not selection',()=>{const s=exercise();aircraft(s,2);measureTwice(s);s.locked=s.selected;const m=s.fire('SEMI_ACTIVE_RADAR');const original=m.target;s.select(s.aircraft[1].id);s.step(.1);assert.equal(m.target,original);s.locked=s.selected;s.step(.1);assert.equal(m.target,s.selected);assert.ok(s.log.some(l=>l.message.includes('illumination retarget')));});
test('IR seeker independently acquires a nearby heat source and intercepts it',()=>{const s=exercise({attackerEvasion:0});aircraft(s);s.aircraft[0].y=-12;s.irst=true;s.time=3;s.updateIr();s.time=5;s.updateIr();s.selected=s.aircraft[0].id;const m=s.fire('IR');assert.ok(m);s.irTracks.clear();s.radar=false;s.irst=false;s.step(1);assert.equal(m.state,'SEEKER LOCK');s.step(18);assert.ok(s.kills>=1);assert.equal(s.channels.size,0);});
