import {Simulation,rangeOf,bearingOf} from './engine.js';
import {sweepInterval,ICONS} from './config.js';
import {AIRCRAFT} from './aircraft-config.js';
import {RUSSIAN_WEAPON_CATALOGUE,FIELD_STATUS} from './weapon-catalogue.js';
const $=id=>document.getElementById(id),stage=$('stage'),canvas=$('radar'),ctx=canvas.getContext('2d');
let sim=new Simulation(),playing=false,paused=false,timeScale=1,viewRange=450,last=performance.now(),uiTimer=0,lastLog=-1;
const images={};for(const file of Object.values(ICONS)){const img=new Image();img.src='assets/'+file;images[file]=img;}
const green='#00efa9',muted='#74ae8d';
function fit(){const factor=Math.min(innerWidth/1680,innerHeight/945);stage.style.transform='scale('+factor+')';canvas.width=canvas.clientWidth;canvas.height=canvas.clientHeight;}
addEventListener('resize',fit);fit();
function timestamp(t){return String(Math.floor(t/60)).padStart(2,'0')+':'+String(Math.floor(t%60)).padStart(2,'0');}
function start(){sim=new Simulation();playing=true;paused=false;timeScale=1;lastLog=-1;$('menu').classList.add('hidden');$('end').classList.add('hidden');$('pause').textContent='PAUSE';$('speed').textContent='1× TIME';renderUI();}
$('play').onclick=start;$('restart').onclick=start;
let guidePaused=false;function openGuide(){guidePaused=paused;paused=true;$('guide').classList.remove('hidden');}function closeGuide(){$('guide').classList.add('hidden');paused=guidePaused;}
function addReferenceField(dl,label,value){const dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=label;dd.textContent=value;dl.append(dt,dd);}
for(const p of Object.values(AIRCRAFT)){const row=document.createElement('dl');row.className='reference-fields';addReferenceField(row,p.name,p.role+' · TASK: '+p.mission);$('aircraft-reference').append(row);}
function referenceValue(w,key,unit=''){const status=w.fieldStatus[key];if(status===FIELD_STATUS.UNKNOWN)return 'Not listed';if(status===FIELD_STATUS.NOT_APPLICABLE)return 'N/A';if(status===FIELD_STATUS.RELEASE_DEPENDENT)return 'Depends on release';return w[key]+(unit?' '+unit:'');}
for(const w of RUSSIAN_WEAPON_CATALOGUE){const entry=document.createElement('details');entry.className='weapon-entry';entry.dataset.weaponId=w.id;const title=document.createElement('summary');title.textContent=w.name+' · '+w.guidance.label;entry.append(title);const dl=document.createElement('dl');dl.className='reference-fields';
  for(const [label,key,unit]of [['Max missile speed','maxSpeedMach','Mach'],['Wiki launch range','launchRangeKm','km'],['Max travel range','maxTravelRangeKm','km'],['Carrier max release speed','maxAircraftReleaseSpeedKmh','km/h'],['Guidance lifetime','guidanceTimeSeconds','s'],['Weapon mass','massKg','kg'],['Explosive filler','explosiveFillerMassKg','kg'],['TNT equivalent','tntEquivalentKg','kg'],['Max G','maxG','G']])addReferenceField(dl,label,referenceValue(w,key,unit));
  addReferenceField(dl,'Seeker lock',w.seekerLockRangeByAspectKm?'Rear '+w.seekerLockRangeByAspectKm.rear+' km / all-aspect '+w.seekerLockRangeByAspectKm.allAspect+' km':referenceValue(w,'seekerLockRangeKm','km'));
  addReferenceField(dl,'Wiki seeker band',w.seekerBandLabels?.join(' / ')||(w.category==='UNGUIDED_BOMB'?'N/A':'Not listed'));
  addReferenceField(dl,'Role',w.role.replaceAll('_',' '));addReferenceField(dl,'Source',w.provenance.reportedPanel+' · supplied guide values');
  if(w.notes.length)addReferenceField(dl,'Notes',w.notes.join(' '));entry.append(dl);$('weapon-catalogue').append(entry);}
$('help').onclick=openGuide;$('menu-guide').onclick=openGuide;$('close-guide').onclick=closeGuide;
$('pause').onclick=()=>{paused=!paused;$('pause').textContent=paused?'RESUME':'PAUSE';};
$('speed').onclick=()=>{timeScale=timeScale===8?1:timeScale*2;$('speed').textContent=timeScale+'× TIME';};
$('radar-toggle').onclick=()=>sim.toggleSensor('radar');$('ir-toggle').onclick=()=>sim.toggleSensor('irst');$('reset').onclick=()=>sim.resetRadar();$('auto').onclick=()=>sim.setAuto();$('next').onclick=()=>sim.nextTarget();$('lock').onclick=()=>sim.lock();$('unlock').onclick=()=>sim.unlock();$('fire').onclick=()=>sim.fire();
document.querySelectorAll('[data-range]').forEach(b=>b.onclick=()=>{viewRange=Number(b.dataset.range);document.querySelectorAll('[data-range]').forEach(x=>x.classList.toggle('active',x===b));});
const launcherSvg='<svg viewBox="0 0 120 78" aria-hidden="true"><path d="M8 60h83v-15h18v15h7v9H8z M92 47V33h12l9 14 M14 51l13-9 37-30 7 8-40 35z M27 42l-7-8 39-31 8 8 M30 47l-7-8 39-31 8 8 M43 57v-8l7-8 M52 40l-7 14"/><circle cx="23" cy="68" r="7"/><circle cx="43" cy="68" r="7"/><circle cx="99" cy="68" r="7"/><path d="M19 68h8 M39 68h8 M95 68h8 M10 59h76"/></svg>';
for(let i=0;i<4;i++){const b=document.createElement('button');b.className='launcher panel';b.id='launcher-'+i;b.innerHTML='<h2>0'+(6+i)+' / LAUNCHER '+(i+1)+'</h2><div class="launcher-content">'+launcherSvg+'<div class="launcher-stats">MIM-225A<br><span class="state">READY</span><br><b class="rounds">4 / 4</b></div></div><div class="ammo-bars"></div><div class="reload-hint">SELECT TO FIRE</div>';b.onclick=()=>{if(sim.launcher===i)sim.reload(i);else sim.launcher=i;};$('launchers').append(b);}
function text(id,value){$(id).textContent=value;}
function renderUI(){text('clock',timestamp(sim.time));text('cmd',Math.max(0,100-sim.hits*25)+'%');text('radar-health',sim.radar?'ON':'OFF');text('ir-health',sim.irst?'ON':'OFF');const incoming=[...sim.contacts.values()].filter(c=>c.kind==='MISSILE'&&sim.time-c.lastSeen<sim.cfg.trackTimeout);text('battery-title',incoming.length?'INCOMING MISSILE · SAM BATTERY':sim.hits?'SAM BATTERY UNDER ATTACK':'SAM BATTERY OPERATIONAL');text('track-count',sim.trackCount()+' / '+sim.equipment.tracks);text('detection-count',sim.contacts.size+' RADAR CONTACTS · '+sim.irTracks.size+' IRST CUES');text('channels',sim.channels.size+' / '+sim.equipment.channels);const loaded=sim.launchers.reduce((n,l)=>n+l.loaded,0);text('loaded',loaded);text('reserve',sim.reserve);text('total',loaded+sim.reserve);text('scan-meta','SCAN '+sim.cfg.scanRating.toFixed(2)+' · '+sweepInterval(sim.cfg.scanRating).toFixed(2)+' s');text('range-meta','VIEW '+viewRange+' km');text('wave','EXERCISE / '+timestamp(sim.time));text('score','KILLS '+sim.kills+' · INT '+sim.intercepts+' · HITS '+sim.hits+'/4');
 for(const [name,id]of [['radar','radar-toggle'],['irst','ir-toggle']]){const b=$(id),sw=sim.switches[name];b.querySelector('b').textContent=sw?'SWITCHING':sim[name]?'ON':'OFF';b.querySelector('.led').className='led '+(sw?'switching':sim[name]?'':'off');b.classList.toggle('active',sim[name]);}
 $('auto').querySelector('b').textContent=sim.auto?'ON':'OFF';$('auto').classList.toggle('active',sim.auto);const reason=sim.fireReason();$('fire').disabled=!!reason;text('fire-reason',reason||'Ready · Launcher '+(sim.launcher+1));const old=sim.overflow();text('overflow',!reason&&old?'NEXT LAUNCH: '+old.id+' loses channel → '+(old.guidance==='ACTIVE_RADAR'?'EARLY SEARCH':'GUIDANCE LOSS'):'');
 const list=$('track-list');list.replaceChildren();const tracks=[...sim.contacts.values()].filter(c=>c.tracked).sort((a,b)=>(b.kind==='MISSILE')-(a.kind==='MISSILE')||a.range-b.range);if(!tracks.length){const p=document.createElement('div');p.className='empty-state';p.textContent='NO USABLE TWS TRACKS\nSweeps build measurement history.\nDetections remain visible on radar.';p.style.whiteSpace='pre-line';list.append(p);}for(const c of tracks){const p=sim.estimate(c),b=document.createElement('button');b.className='track-row'+(sim.selected===c.id?' selected':'')+(sim.isStale(c)?' stale':'');b.innerHTML='<span class="track-label"></span><span>'+rangeOf(p).toFixed(0)+'</span><span>'+c.altitude.toFixed(1)+'</span><span>'+Math.round(c.speed)+'</span><span class="state">'+(sim.locked===c.id?'LOCK':sim.isStale(c)?'STALE':'TWS')+'</span>';b.firstChild.textContent=c.id+' '+(c.type||'Unknown');b.firstChild.style.color=c.allegiance==='HOSTILE'?'#ff6767':c.allegiance==='FRIENDLY'?green:'#c7d5ce';b.onclick=()=>sim.select(c.id);list.append(b);}
 const c=sim.getSelected();text('target-id',c?.id||'—');const usable=c?.tracked;const p=c?sim.estimate(c):null;const age=c?sim.time-(usable?c.trackTime:c.lastSeen):0;const entries=[['TYPE',c?.recognized?c.type:'UNKNOWN'],['ALLEGIANCE',c?.allegiance||'UNKNOWN'],['RANGE',c?(c.rangeEstimated?'≈ ':'')+(usable?rangeOf(p):c.range).toFixed(1)+' km':'—'],['ALTITUDE',usable?(c.altitude*1000).toFixed(0)+' m':'—'],['SPEED',usable?Math.round(c.speed)+' km/h':'—'],['HEADING',usable?Math.round(c.heading)+'°':c?.ir?'Bearing '+Math.round(c.bearing)+'°':'—'],['CONFIDENCE',c?.confidence?Math.round(c.confidence*100)+'%':'UNCONFIRMED'],['DATA AGE',c?age.toFixed(1)+' s':'—']];const dl=$('target-info');dl.replaceChildren();for(const [k,v]of entries){const dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=k;dd.textContent=v;if(v==='HOSTILE')dd.style.color='#ff6767';dl.append(dt,dd);}const file=c?sim.icon(c):ICONS.unknown;$('target-image').src='assets/'+file;text('target-source',c?.source||'NO CONTACT');text('target-state',c?(sim.locked===c.id?'RADAR LOCK':sim.lockAttempt?.id===c.id?'LOCK ACQUIRING':sim.isStale(c)?'STALE TRACK':usable?'TWS · QUALITY '+Math.round(sim.trackQuality(c)*100)+'%':c.ir?'PASSIVE IRST CUE · RANGE ESTIMATE':'DETECTION ONLY · NO VELOCITY'):'Select a detected contact');
 for(let i=0;i<4;i++){const l=sim.launchers[i],b=$('launcher-'+i);b.classList.toggle('active',sim.launcher===i);b.querySelector('.state').textContent=l.reload>0?'RELOAD '+Math.ceil(l.reload)+'s':l.loaded?'READY':'EMPTY';b.querySelector('.rounds').textContent=l.loaded+' / '+sim.cfg.roundsPerLauncher;b.querySelector('.ammo-bars').innerHTML=Array.from({length:sim.cfg.roundsPerLauncher},(_,j)=>'<span class="'+(j>=l.loaded?'empty':'')+'"></span>').join('');b.querySelector('.reload-hint').textContent=sim.launcher===i?'SELECTED · TAP TO RELOAD':'SELECT TO FIRE';}
 text('missile-status',sim.missiles.filter(m=>m.alive).slice(-3).map(m=>m.id+' '+m.state).join(' · '));
 if(sim.log.length!==lastLog||lastLog===250){lastLog=sim.log.length;const log=$('log');log.replaceChildren();for(const entry of sim.log.slice(-45)){const row=document.createElement('div');row.className='log-entry'+(/launched|SEEKER LOCK|destroyed|transferred|lost|hit/.test(entry.message)?' event':'');const time=document.createElement('time'),span=document.createElement('span');time.textContent=timestamp(entry.time);span.textContent=entry.message;row.append(time,span);log.append(row);}log.scrollTop=log.scrollHeight;}
 if(sim.ended){$('end').classList.remove('hidden');text('end-title',sim.hits>=4?'BATTERY LOST':'EXERCISE COMPLETE');text('end-stats',sim.kills+' aircraft destroyed · '+sim.intercepts+' missiles intercepted · '+sim.fired+' SAMs fired · '+sim.hits+'/4 battery hits');}
}
function geometry(){const w=canvas.width,h=canvas.height,r=Math.min(w*.47,h*.465),x=w/2,y=h/2;return {w,h,r,x,y};}
function drawIcon(file,x,y,size,rotation=0,alpha=1){const img=images[file];if(!img?.complete||!img.naturalWidth)return;ctx.save();ctx.globalAlpha=alpha;ctx.globalCompositeOperation="screen";ctx.translate(x,y);ctx.rotate(rotation);const s=size/Math.max(img.naturalWidth,img.naturalHeight);ctx.drawImage(img,-img.naturalWidth*s/2,-img.naturalHeight*s/2,img.naturalWidth*s,img.naturalHeight*s);ctx.restore();}
function drawRadar(){const {w,h,r,x,y}=geometry(),toPixel=p=>({x:x+p.x/viewRange*r,y:y+p.y/viewRange*r});ctx.clearRect(0,0,w,h);const bg=ctx.createRadialGradient(x,y,0,x,y,r);bg.addColorStop(0,'#042515');bg.addColorStop(1,'#000b05');ctx.fillStyle=bg;ctx.fillRect(0,0,w,h);ctx.save();ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.clip();ctx.strokeStyle='#0b2f1b';ctx.lineWidth=.7;for(let i=0;i<w;i+=32){ctx.beginPath();ctx.moveTo(i,0);ctx.lineTo(i,h);ctx.stroke();}for(let i=0;i<h;i+=32){ctx.beginPath();ctx.moveTo(0,i);ctx.lineTo(w,i);ctx.stroke();}
 for(let ring=1;ring<=4;ring++){ctx.strokeStyle=ring===4?'#00b880':'#007544';ctx.lineWidth=ring===4?1.7:.8;ctx.beginPath();ctx.arc(x,y,r*ring/4,0,Math.PI*2);ctx.stroke();ctx.fillStyle=muted;ctx.font='12px monospace';ctx.fillText(Math.round(viewRange*ring/4),x+7,y-r*ring/4+17);}for(let i=0;i<12;i++){const a=i*Math.PI/6;ctx.strokeStyle=i%3===0?'#008d62':'#075831';ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x+Math.sin(a)*r,y-Math.cos(a)*r);ctx.stroke();}
 if(sim.radar){for(let i=0;i<35;i++){const a=sim.phase-Math.PI/2-i*.012;ctx.fillStyle='rgba(0,239,110,'+(.012*(1-i/35))+')';ctx.beginPath();ctx.moveTo(x,y);ctx.arc(x,y,r,a-.016,a+.004);ctx.fill();}ctx.strokeStyle='#00d38888';ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x+Math.sin(sim.phase)*r,y-Math.cos(sim.phase)*r);ctx.stroke();}
 // Display uses measured or predicted sensor contacts only.
 for(const c of sim.visible()){const p=sim.estimate(c),pixel=toPixel(p);if(rangeOf(p)>viewRange)continue;const age=sim.time-c.lastSeen,alpha=c.tracked?1:Math.max(.25,1-age/sim.cfg.contactTimeout);const size=28;const rotation=c.tracked?(c.heading||0)*Math.PI/180:0;drawIcon(sim.icon(c),pixel.x,pixel.y,size,rotation,alpha);ctx.save();ctx.strokeStyle=c.allegiance==='HOSTILE'?'#ff7272':c.allegiance==='FRIENDLY'?green:'#c9d6cd';ctx.lineWidth=1.2;if(sim.locked===c.id||c.tracked){ctx.setLineDash(sim.locked===c.id?[]:[2,4]);ctx.beginPath();ctx.arc(pixel.x,pixel.y,21,0,Math.PI*2);ctx.stroke();}ctx.setLineDash([]);if(sim.selected===c.id){ctx.strokeStyle=green;const d=29;for(const [sx,sy]of [[-1,-1],[1,-1],[-1,1],[1,1]]){ctx.beginPath();ctx.moveTo(pixel.x+sx*d,pixel.y+sy*(d-8));ctx.lineTo(pixel.x+sx*d,pixel.y+sy*d);ctx.lineTo(pixel.x+sx*(d-8),pixel.y+sy*d);ctx.stroke();}}ctx.globalAlpha=alpha;ctx.font='10px monospace';ctx.fillStyle=muted;ctx.fillText(c.id,pixel.x+24,pixel.y+3);if(c.tracked&&sim.isStale(c)){ctx.fillStyle='#edc371';ctx.fillText('STALE',pixel.x+24,pixel.y+15);}if(c.ir&&!c.tracked){ctx.fillStyle='#70cbae';ctx.fillText('IR',pixel.x+24,pixel.y+15);}ctx.restore();}
 for(const m of sim.missiles){if(!m.alive||rangeOf(m)>viewRange)continue;const p=toPixel(m);ctx.save();if(m.channel){ctx.strokeStyle=m.guidance==='SEMI_ACTIVE_RADAR'&&m.state==='GUIDANCE LOST'?'#907a4588':'#00efa960';ctx.setLineDash(m.guidance==='ACTIVE_RADAR'?[3,6]:[]);ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(p.x,p.y);ctx.stroke();}if(m.state==='SEEKER LOCK'){if(m.acquired){const target=toPixel(m.aim);ctx.setLineDash([]);ctx.strokeStyle='#00efa980';ctx.beginPath();ctx.moveTo(p.x,p.y);ctx.lineTo(target.x,target.y);ctx.stroke();}}ctx.restore();drawIcon(ICONS.player,p.x,p.y,22,m.angle+Math.PI/2);ctx.fillStyle=green;ctx.font='9px monospace';ctx.fillText(m.id+' '+(m.state==='SEARCHING'?'SEARCH':m.state==='SEEKER LOCK'?'SEEKER':'MID'),p.x+13,p.y+9);}
 for(const e of sim.effects){const p=toPixel(e),age=sim.time-e.born;ctx.strokeStyle='rgba(215,255,229,'+(1-age/2)+')';ctx.lineWidth=1;ctx.beginPath();ctx.arc(p.x,p.y,8+age*19,0,Math.PI*2);ctx.stroke();}
 ctx.restore();ctx.fillStyle=green;ctx.font='18px monospace';ctx.textAlign='center';ctx.fillText('N',x,y-r-5);ctx.fillText('S',x,y+r+20);ctx.fillText('W',x-r-18,y+6);ctx.fillText('E',x+r+18,y+6);ctx.fillStyle=green;ctx.beginPath();ctx.arc(x,y,6,0,Math.PI*2);ctx.fill();ctx.font='9px monospace';ctx.fillText('HORIZON SHIELD',x,y+21);ctx.textAlign='left';ctx.fillStyle=muted;ctx.font='11px monospace';ctx.fillText('DET 455 / TWS 315 / LOCK 310 km',16,21);if(!sim.radar){ctx.textAlign='center';ctx.fillStyle='#93a69a';ctx.font='20px monospace';ctx.fillText('RADAR OFF · CONTACTS COASTING',x,32);ctx.textAlign='left';}}
canvas.addEventListener('pointerdown',e=>{const rect=canvas.getBoundingClientRect(),{r,x,y}=geometry(),px=(e.clientX-rect.left)/rect.width*canvas.width,py=(e.clientY-rect.top)/rect.height*canvas.height;let closest=null,best=40;for(const c of sim.visible()){const p=sim.estimate(c);if(rangeOf(p)>viewRange)continue;const d=Math.hypot(x+p.x/viewRange*r-px,y+p.y/viewRange*r-py);if(d<best){best=d;closest=c.id;}}if(closest)sim.select(closest);});
addEventListener('keydown',e=>{if(!playing||!$('guide').classList.contains('hidden'))return;if(e.code==='Space'){e.preventDefault();sim.fire();}if(e.code==='Tab'){e.preventDefault();sim.nextTarget();}if(e.code==='KeyL')sim.lock();if(e.code==='KeyU')sim.unlock();if(e.code==='KeyP')$('pause').click();if(/^Digit[1-4]$/.test(e.code))sim.launcher=Number(e.code.slice(-1))-1;});
function frame(now){const elapsed=Math.min(.1,(now-last)/1000);last=now;if(playing&&!paused)sim.step(elapsed*timeScale);uiTimer+=elapsed;if(uiTimer>.15){uiTimer=0;renderUI();}drawRadar();requestAnimationFrame(frame);}renderUI();requestAnimationFrame(frame);
// Controlled QA interface exposes the same simulation used by the playable UI.
window.AirDefense={get simulation(){return sim;},start,render:()=>{renderUI();drawRadar();},pause:()=>{paused=true;$('pause').textContent='RESUME';},get state(){return {playing,paused,timeScale,viewRange};}};
